#!/bin/bash

export CLASSPATH=.:../lib/junit-4.12.jar:../lib/hamcrest-all-1.3.jar

echo "Compiling..."
echo

javac -d . ../src/GPSException.java || exit 3
javac -d . ../src/Point.java || exit 3
javac -d . ../src/Track.java || exit 3

javac BasicTests.java || exit 2

java BasicTests
